<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>true</ImplicitUsings>
        <IncludeSymbols>true</IncludeSymbols>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <TargetFramework>netstandard2.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" Version="2026.2.0" PrivateAssets="All"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.12" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.12" />
        <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.401" PrivateAssets="All" />
        <PackageReference Include="NodaTime" Version="3.3.5" />
    </ItemGroup>

</Project>
